name: Lint and build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies & build
        run: |
          yarn
          yarn build
        env: |
          ALGOLIA_APP_ID: dummy
          ALGOLIA_API_KEY: dummy
          ALGOLIA_INDEX_NAME: dummy

      - name: Lint
        run: |
          yarn lint
          yarn format
